// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService reports app/status/library data.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetModelError returns the embedder's load error (for the status pill).
 */
export function GetModelError(): $CancellablePromise<string> {
    return $Call.ByID(1355043894);
}

/**
 * GetPlatform returns the OS ("windows", "darwin", "linux").
 */
export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByID(2503933164);
}

/**
 * GetStatus returns the status summary: library stats + model state.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1831479589).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetVersion returns the app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(712846061);
}

/**
 * ListCollections returns all indexed collections with counts, ordered by name.
 */
export function ListCollections(): $CancellablePromise<$models.Collection[]> {
    return $Call.ByID(1339457758).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListDocuments returns the documents of a collection (optionally one source).
 */
export function ListDocuments(collectionID: number, sourceID: number): $CancellablePromise<$models.Document[]> {
    return $Call.ByID(1318390221, collectionID, sourceID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListSources returns the sources of a collection, ordered by path.
 */
export function ListSources(collectionID: number): $CancellablePromise<$models.Source[]> {
    return $Call.ByID(553118937, collectionID).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.Collection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Document.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Source.createFrom;
const $$createType6 = $Create.Array($$createType5);
