// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService reports app/status/library data.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCPUCount returns the number of logical CPUs available to the process —
 * the ceiling the Settings UI uses for the model's CPU-threads slider
 * (0 = use all of them).
 */
export function GetCPUCount(): $CancellablePromise<number> {
    return $Call.ByID(899550166);
}

/**
 * GetDocument returns one chunk with its full text and metadata, for the
 * reading pane.
 */
export function GetDocument(id: number): $CancellablePromise<$models.Document> {
    return $Call.ByID(4208047110, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetModelError returns the embedder's load error (for the status pill).
 */
export function GetModelError(): $CancellablePromise<string> {
    return $Call.ByID(1355043894);
}

/**
 * GetPlatform returns the OS ("windows", "darwin", "linux").
 */
export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByID(2503933164);
}

/**
 * GetStatus returns the status summary: library stats + model state.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1831479589).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetVersion returns the app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(712846061);
}

/**
 * ListCollections returns all indexed collections with counts, ordered by name.
 */
export function ListCollections(): $CancellablePromise<$models.Collection[]> {
    return $Call.ByID(1339457758).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListDocumentsPage returns one page of a collection's chunk stream, ordered by
 * source then chunk. The rows deliberately carry no content: the stream is
 * paged indefinitely and the selected chunk's text comes from GetDocument.
 */
export function ListDocumentsPage(collectionID: number, cursor: string, backward: boolean): $CancellablePromise<$models.DocumentPage> {
    return $Call.ByID(1199931038, collectionID, cursor, backward).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListSourcesPage returns one page of a collection's sources ordered by path.
 * backward=true pages towards the start of the list; cursor is opaque and comes
 * from a previous page ("" for the first page).
 */
export function ListSourcesPage(collectionID: number, cursor: string, backward: boolean): $CancellablePromise<$models.SourcePage> {
    return $Call.ByID(757967130, collectionID, cursor, backward).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenFile opens a file or folder with the OS default application.
 */
export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3971017067, path);
}

/**
 * RevealInFolder selects a file in the OS file manager (opens the parent
 * folder for a directory).
 */
export function RevealInFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(1720853207, path);
}

// Private type creation functions
const $$createType0 = $models.Document.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $models.Collection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DocumentPage.createFrom;
const $$createType5 = $models.SourcePage.createFrom;
