// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IndexService exposes configuration, indexing, and pruning to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";

/**
 * AddSourcePath adds a source path. kind is "vault", "calibre", "project", or
 * "repo"; name is the collection name for project/repo (ignored otherwise).
 */
export function AddSourcePath(kind: string, name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1004018315, kind, name, path);
}

/**
 * GetConfig returns the current configuration.
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2113296768).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IndexAll starts pruning + indexing every enabled, configured collection.
 */
export function IndexAll(force: boolean): $CancellablePromise<void> {
    return $Call.ByID(2589092493, force);
}

/**
 * IndexCollection starts indexing one collection in the background, emitting
 * indexing:progress and indexing:complete events.
 */
export function IndexCollection(name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(180963702, name, force);
}

/**
 * IsIndexing reports whether an index run is in progress.
 */
export function IsIndexing(): $CancellablePromise<boolean> {
    return $Call.ByID(364703326);
}

/**
 * Prune removes stale sources from a collection ("all" or "" for everything).
 */
export function Prune(name: string): $CancellablePromise<indexer$0.PruneResult> {
    return $Call.ByID(624196390, name).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveSourcePath removes a source path from a config section.
 */
export function RemoveSourcePath(kind: string, name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2260568612, kind, name, path);
}

/**
 * SetConfig saves the configuration and applies its side effects
 * (start-on-login). Auto-reindex is read live by the loop in main.
 */
export function SetConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(721337284, cfg);
}

/**
 * ToggleCollectionEnabled enables/disables a collection for indexing.
 */
export function ToggleCollectionEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3287772159, name, enabled);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = indexer$0.PruneResult.createFrom;
