// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IndexService exposes configuration, indexing, and pruning to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddSourcePath adds a source path. kind is "vault", "calibre", "project", or
 * "repo"; name is the collection name for project/repo (ignored otherwise).
 */
export function AddSourcePath(kind: string, name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1004018315, kind, name, path);
}

/**
 * CancelIndexing aborts the active index run, if any, and reports whether one
 * was running.
 */
export function CancelIndexing(): $CancellablePromise<boolean> {
    return $Call.ByID(4016222948);
}

/**
 * DeleteCollection removes a collection and everything cascading from it:
 * its sources, documents (FTS cleared via the delete trigger), float + binary
 * embeddings, and the collection row. It also removes the collection's config
 * entry — an obsidian/calibre collection owns all its vault/library paths, a
 * project/repo collection owns its whole group — so it does not silently
 * resurrect on the next index pass. Files on disk are never touched. Works
 * even when the collection was never indexed (config-only). Returns the
 * number of documents removed.
 */
export function DeleteCollection(name: string): $CancellablePromise<number> {
    return $Call.ByID(3393632225, name);
}

/**
 * DeleteDocuments removes the given chunks (documents) and their float +
 * binary embeddings in one pass; FTS is cleared via the delete trigger. The
 * source and collection rows stay, so re-indexing restores the deleted
 * chunks. An empty list is a no-op. Errors if an index run is in progress.
 * Returns the number of documents removed.
 */
export function DeleteDocuments(docIDs: number[]): $CancellablePromise<number> {
    return $Call.ByID(2694537237, docIDs);
}

/**
 * DeleteSource removes one indexed source and everything cascading from it:
 * its documents (FTS cleared via the delete trigger) and its float + binary
 * embeddings. The source's path stays in config — this is one file among many
 * — so the next index pass will re-add it if the file still exists on disk.
 * Returns the number of documents removed, and errors if the source does not
 * exist or an index run is in progress.
 */
export function DeleteSource(sourceID: number): $CancellablePromise<number> {
    return $Call.ByID(2650919656, sourceID);
}

/**
 * GetConfig returns the current configuration.
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2113296768).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetIndexingState returns a snapshot of the active index run (if any) so a
 * frontend that reloads or reconnects mid-run can rebuild the indexing UI
 * instead of showing nothing. Live updates still arrive as events; this only
 * seeds the initial state on (re)load.
 */
export function GetIndexingState(): $CancellablePromise<$models.IndexState> {
    return $Call.ByID(148853163).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IndexAll starts pruning + indexing every enabled, configured collection.
 */
export function IndexAll(force: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(2589092493, force);
}

/**
 * IndexCollection starts indexing one collection in the background, emitting
 * indexing:file, indexing:progress, and indexing:complete / indexing:cancelled
 * events. Returns false when another index run is already in progress, so the
 * frontend never gets stuck in an "indexing" state for a run that never
 * actually started.
 */
export function IndexCollection(name: string, force: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(180963702, name, force);
}

/**
 * IndexSynchronous indexes one collection in the calling goroutine and
 * returns the run summary. It is used by the MCP vectile_index write tool so
 * the client gets the result directly. It still emits the indexing events, so
 * an open frontend Index view stays in sync. Errors when another index run is
 * already in progress.
 */
export function IndexSynchronous(name: string, force: boolean): $CancellablePromise<indexer$0.IndexResult | null> {
    return $Call.ByID(2915466095, name, force).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsIndexing reports whether an index run is in progress.
 */
export function IsIndexing(): $CancellablePromise<boolean> {
    return $Call.ByID(364703326);
}

/**
 * Prune removes stale sources from a collection ("all" or "" for everything).
 */
export function Prune(name: string): $CancellablePromise<indexer$0.PruneResult> {
    return $Call.ByID(624196390, name).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RemoveSourcePath removes a source path from a config section.
 */
export function RemoveSourcePath(kind: string, name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2260568612, kind, name, path);
}

/**
 * SetConfig saves the configuration and applies its side effects
 * (start-on-login). Auto-reindex is read live by the loop in main.
 */
export function SetConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(721337284, cfg);
}

/**
 * ToggleCollectionEnabled enables/disables a collection for indexing.
 */
export function ToggleCollectionEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3287772159, name, enabled);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.IndexState.createFrom;
const $$createType3 = indexer$0.IndexResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = indexer$0.PruneResult.createFrom;
