// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as embeddings$0 from "../embeddings/models.js";

/**
 * CatalogModel is one pre-approved embedding model vectile can fetch for the
 * user. Each carries the SHA-256 verified after download so a corrupted or
 * tampered file is never loaded, plus a link out to the upstream page for
 * users who prefer to read about or inspect it.
 */
export class CatalogModel {
    "key": string;
    "name": string;
    "file": string;
    "url": string;
    "dimensions": number;
    "sizeBytes": number;
    "quantization": string;
    "language": string;
    "recommended": boolean;
    "description": string;
    "hfUrl": string;

    /** Creates a new CatalogModel instance. */
    constructor($$source: Partial<CatalogModel> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("quantization" in $$source)) {
            this["quantization"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("hfUrl" in $$source)) {
            this["hfUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogModel instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogModel($$parsedSource as Partial<CatalogModel>);
    }
}

/**
 * Collection is a library collection with counts and enabled state.
 * NeedsReindex is true when the collection has indexed documents but no
 * embeddings — typically right after switching to a model with a different
 * embedding dimension, which empties the vector tables until re-indexing.
 */
export class Collection {
    "id": number;
    "name": string;
    "type": string;
    "description": string;
    "sources": number;
    "chunks": number;
    "created": string;
    "enabled": boolean;
    "needsReindex": boolean;
    "lastIndexed": string;

    /** Creates a new Collection instance. */
    constructor($$source: Partial<Collection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = 0;
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("needsReindex" in $$source)) {
            this["needsReindex"] = false;
        }
        if (!("lastIndexed" in $$source)) {
            this["lastIndexed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     */
    static createFrom($$source: any = {}): Collection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection($$parsedSource as Partial<Collection>);
    }
}

/**
 * Document is one chunked document (a browse reading pane), with its full text.
 */
export class Document {
    "id": number;
    "sourceId": number;
    "collectionId": number;
    "chunkIndex": number;
    "title": string;
    "content": string;
    "metadata": any;

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("chunkIndex" in $$source)) {
            this["chunkIndex"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document($$parsedSource as Partial<Document>);
    }
}

/**
 * DocumentPage is one keyset page of a collection's chunk stream, in stream
 * order. Before and After are opaque cursors for the neighbouring pages; ""
 * means that side ends there.
 */
export class DocumentPage {
    "documents": DocumentSummary[];
    "before": string;
    "after": string;

    /** Creates a new DocumentPage instance. */
    constructor($$source: Partial<DocumentPage> = {}) {
        if (!("documents" in $$source)) {
            this["documents"] = [];
        }
        if (!("before" in $$source)) {
            this["before"] = "";
        }
        if (!("after" in $$source)) {
            this["after"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentPage instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("documents" in $$parsedSource) {
            $$parsedSource["documents"] = $$createField0_0($$parsedSource["documents"]);
        }
        return new DocumentPage($$parsedSource as Partial<DocumentPage>);
    }
}

/**
 * DocumentSummary is one row in the paged Browse chunk stream: the fields the
 * list needs, without the text. The stream is paged indefinitely, so Content and
 * Metadata come from GetDocument for the selected chunk only.
 */
export class DocumentSummary {
    "id": number;
    "sourceId": number;
    "collectionId": number;
    "chunkIndex": number;
    "title": string;
    "sourcePath": string;
    "sourceType": string;

    /** Creates a new DocumentSummary instance. */
    constructor($$source: Partial<DocumentSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("chunkIndex" in $$source)) {
            this["chunkIndex"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentSummary($$parsedSource as Partial<DocumentSummary>);
    }
}

/**
 * IndexFileProgress is emitted per successfully indexed file during a run,
 * scoped to the collection being indexed so the frontend can increment its
 * per-collection file count.
 */
export class IndexFileProgress {
    "collection": string;
    "file": string;
    "indexed": number;
    "total": number;

    /** Creates a new IndexFileProgress instance. */
    constructor($$source: Partial<IndexFileProgress> = {}) {
        if (!("collection" in $$source)) {
            this["collection"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("indexed" in $$source)) {
            this["indexed"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexFileProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexFileProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexFileProgress($$parsedSource as Partial<IndexFileProgress>);
    }
}

/**
 * IndexState is a snapshot of the active index run, returned by
 * GetIndexingState so a frontend that reloads or reconnects mid-run can
 * rebuild its indexing UI instead of showing nothing. Live updates still
 * arrive as events; this is only the initial state on (re)load.
 */
export class IndexState {
    "active": boolean;
    "all": boolean;
    "collections": { [_ in string]?: IndexFileProgress };

    /** Creates a new IndexState instance. */
    constructor($$source: Partial<IndexState> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("all" in $$source)) {
            this["all"] = false;
        }
        if (!("collections" in $$source)) {
            this["collections"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexState instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexState {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField2_0($$parsedSource["collections"]);
        }
        return new IndexState($$parsedSource as Partial<IndexState>);
    }
}

/**
 * ModelDownloadState is a snapshot of the active download, returned by
 * GetDownloadState so a reloading frontend can rebuild its progress UI.
 */
export class ModelDownloadState {
    "active": boolean;
    "key": string;
    "status": string;
    "downloaded": number;
    "total": number;
    "percent": number;
    "speed": number;
    "error": string;

    /** Creates a new ModelDownloadState instance. */
    constructor($$source: Partial<ModelDownloadState> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelDownloadState instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelDownloadState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelDownloadState($$parsedSource as Partial<ModelDownloadState>);
    }
}

/**
 * SetActiveResult reports the outcome of SetActiveModel. NeedsRebuild is true
 * when switching would change the embedding dimension — the switch is NOT
 * applied until the frontend confirms and calls SetActiveModel(force=true).
 */
export class SetActiveResult {
    "needsRebuild": boolean;
    "model": db$0.Model;

    /** Creates a new SetActiveResult instance. */
    constructor($$source: Partial<SetActiveResult> = {}) {
        if (!("needsRebuild" in $$source)) {
            this["needsRebuild"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = (new db$0.Model());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetActiveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SetActiveResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model" in $$parsedSource) {
            $$parsedSource["model"] = $$createField1_0($$parsedSource["model"]);
        }
        return new SetActiveResult($$parsedSource as Partial<SetActiveResult>);
    }
}

/**
 * Source is one indexed source.
 */
export class Source {
    "id": number;
    "collectionId": number;
    "sourceType": string;
    "path": string;
    "chunks": number;
    "lastIndexed": string;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("lastIndexed" in $$source)) {
            this["lastIndexed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * SourcePage is one keyset page of a collection's sources. Before and After are
 * opaque cursors for the neighbouring pages; "" means that side ends there.
 */
export class SourcePage {
    "sources": Source[];
    "before": string;
    "after": string;

    /** Creates a new SourcePage instance. */
    constructor($$source: Partial<SourcePage> = {}) {
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("before" in $$source)) {
            this["before"] = "";
        }
        if (!("after" in $$source)) {
            this["after"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourcePage instance from a string or object.
     */
    static createFrom($$source: any = {}): SourcePage {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField0_0($$parsedSource["sources"]);
        }
        return new SourcePage($$parsedSource as Partial<SourcePage>);
    }
}

/**
 * Status is the app-wide status summary shown in the UI.
 */
export class Status {
    "collections": number;
    "sources": number;
    "chunks": number;
    "dbSize": number;
    "modelState": embeddings$0.State;
    "modelName": string;
    "modelPath": string;
    "modelError": string;
    "lastIndexed": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("collections" in $$source)) {
            this["collections"] = 0;
        }
        if (!("sources" in $$source)) {
            this["sources"] = 0;
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("dbSize" in $$source)) {
            this["dbSize"] = 0;
        }
        if (!("modelState" in $$source)) {
            this["modelState"] = embeddings$0.State.$zero;
        }
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("modelPath" in $$source)) {
            this["modelPath"] = "";
        }
        if (!("modelError" in $$source)) {
            this["modelError"] = "";
        }
        if (!("lastIndexed" in $$source)) {
            this["lastIndexed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = DocumentSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = IndexFileProgress.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = db$0.Model.createFrom;
const $$createType5 = Source.createFrom;
const $$createType6 = $Create.Array($$createType5);
