// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as embeddings$0 from "../embeddings/models.js";

/**
 * Collection is a library collection with counts and enabled state.
 */
export class Collection {
    "id": number;
    "name": string;
    "type": string;
    "description": string;
    "sources": number;
    "chunks": number;
    "created": string;
    "enabled": boolean;

    /** Creates a new Collection instance. */
    constructor($$source: Partial<Collection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = 0;
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     */
    static createFrom($$source: any = {}): Collection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection($$parsedSource as Partial<Collection>);
    }
}

/**
 * Document is one chunked document (a browse leaf).
 */
export class Document {
    "id": number;
    "sourceId": number;
    "collectionId": number;
    "chunkIndex": number;
    "title": string;
    "content": string;
    "metadata": any;

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = 0;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("chunkIndex" in $$source)) {
            this["chunkIndex"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document($$parsedSource as Partial<Document>);
    }
}

/**
 * Source is one indexed source.
 */
export class Source {
    "id": number;
    "collectionId": number;
    "sourceType": string;
    "path": string;
    "chunks": number;
    "lastIndexed": string;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("collectionId" in $$source)) {
            this["collectionId"] = 0;
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("lastIndexed" in $$source)) {
            this["lastIndexed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * Status is the app-wide status summary shown in the UI.
 */
export class Status {
    "collections": number;
    "sources": number;
    "chunks": number;
    "dbSize": number;
    "modelState": embeddings$0.State;
    "modelName": string;
    "modelPath": string;
    "modelError": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("collections" in $$source)) {
            this["collections"] = 0;
        }
        if (!("sources" in $$source)) {
            this["sources"] = 0;
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("dbSize" in $$source)) {
            this["dbSize"] = 0;
        }
        if (!("modelState" in $$source)) {
            this["modelState"] = embeddings$0.State.$zero;
        }
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("modelPath" in $$source)) {
            this["modelPath"] = "";
        }
        if (!("modelError" in $$source)) {
            this["modelError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
