// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService manages installed embedding models: importing a .gguf through
 * the UI, picking the active model, per-model settings, and keeping the
 * models table in sync with the models/ folder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyActiveModel runs at startup: it reconciles the models folder, then
 * loads the active model (or the configured default) with its per-model
 * settings, rebuilding the vector tables if their dimension no longer matches
 * the active model. Returns an error only when the DB/embedder can't be made
 * consistent; a missing model falls back to the default path.
 */
export function ApplyActiveModel(): $CancellablePromise<void> {
    return $Call.ByID(1686711808);
}

/**
 * CancelModelDownload cancels the in-flight model download, if any.
 */
export function CancelModelDownload(): $CancellablePromise<boolean> {
    return $Call.ByID(3373660950);
}

/**
 * DeleteModel removes a model from the table and, when the file lives in the
 * models/ folder, deletes the file too so the folder scan doesn't re-add it.
 * The active model cannot be deleted.
 */
export function DeleteModel(path: string): $CancellablePromise<void> {
    return $Call.ByID(3374659369, path);
}

/**
 * DownloadModel starts a background download of a catalog model: HTTP fetch,
 * SHA-256 verify, GGUF embedding check, then register + activate. Returns
 * whether the download started (false when one is already running, an index
 * run is in flight, or the model is already installed). Progress arrives as
 * model:download-progress events; completion/failure as model:download-complete
 * / model:download-failed.
 */
export function DownloadModel(key: string): $CancellablePromise<boolean> {
    return $Call.ByID(3567360488, key);
}

/**
 * GetDownloadState returns a snapshot of the active download so a reloading
 * frontend can rebuild its progress UI; live updates still arrive as events.
 */
export function GetDownloadState(): $CancellablePromise<$models.ModelDownloadState> {
    return $Call.ByID(1292897846).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportModel copies a .gguf into the models/ folder and registers it. The
 * file is copied so the app owns it and the model survives the original
 * being moved or deleted. It is not auto-activated; the user picks it.
 */
export function ImportModel(srcPath: string): $CancellablePromise<db$0.Model> {
    return $Call.ByID(3637578651, srcPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListModels reconciles the models table with the models/ folder (adding any
 * .gguf that isn't registered, removing rows whose file has vanished) and
 * returns every installed model.
 */
export function ListModels(): $CancellablePromise<db$0.Model[]> {
    return $Call.ByID(4184755701).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListRecommendedModels returns the curated catalog of models the app can
 * download directly.
 */
export function ListRecommendedModels(): $CancellablePromise<$models.CatalogModel[]> {
    return $Call.ByID(2741288292).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetActiveModel makes the model at path active. When the model's embedding
 * dimension differs from the dimension the vector tables were built at, the
 * switch is NOT applied — NeedsRebuild is returned so the frontend can confirm
 * the destructive re-index, then call SetActiveModel(path, force=true).
 */
export function SetActiveModel(path: string, force: boolean): $CancellablePromise<$models.SetActiveResult> {
    return $Call.ByID(859586252, path, force).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateModelSettings updates a model's per-model settings (context window in
 * tokens, embedding batch size, CPU threads). When the edited model is the
 * active one, the new settings apply to the running embedder immediately.
 */
export function UpdateModelSettings(id: number, contextWindow: number, batchSize: number, threads: number): $CancellablePromise<void> {
    return $Call.ByID(2688418022, id, contextWindow, batchSize, threads);
}

// Private type creation functions
const $$createType0 = $models.ModelDownloadState.createFrom;
const $$createType1 = db$0.Model.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CatalogModel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SetActiveResult.createFrom;
