// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OCRService installs and reports the Tesseract plugin. The work lives in
 * backend/ocr; this layer adds the single-flight guard, the progress events,
 * and the state the UI renders.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelOCRInstall cancels an in-flight install, if any.
 */
export function CancelOCRInstall(): $CancellablePromise<boolean> {
    return $Call.ByID(4022925375);
}

/**
 * GetOCRState reports the plugin as it is right now.
 */
export function GetOCRState(): $CancellablePromise<$models.OCRState> {
    return $Call.ByID(1941606847).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InstallOCR starts a background download of the bundle for this platform.
 * Returns whether it started: false when one is already running, when the
 * platform has no bundle, when it is already installed, or when an index run
 * is in flight. Progress arrives as ocr:install-progress, then
 * ocr:install-complete / ocr:install-failed / ocr:install-cancelled.
 */
export function InstallOCR(): $CancellablePromise<boolean> {
    return $Call.ByID(2152838503);
}

/**
 * RemoveOCR deletes the installed bundle. Scans stop being readable until it is
 * installed again; the Settings card offers exactly that.
 */
export function RemoveOCR(): $CancellablePromise<void> {
    return $Call.ByID(3310393162);
}

// Private type creation functions
const $$createType0 = $models.OCRState.createFrom;
