// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService exposes hybrid search to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../search/models.js";

/**
 * Search runs hybrid vector + FTS search with the given filters.
 */
export function Search(query: string, filters: search$0.Filters): $CancellablePromise<search$0.SearchResult[]> {
    return $Call.ByID(2587852292, query, filters).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = search$0.SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
