// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * IndexResult summarises an indexing run.
 */
export class IndexResult {
    "Indexed": number;
    "Skipped": number;
    "Errors": number;
    "TotalFound": number;
    "ErrorMessages": string[];

    /** Creates a new IndexResult instance. */
    constructor($$source: Partial<IndexResult> = {}) {
        if (!("Indexed" in $$source)) {
            this["Indexed"] = 0;
        }
        if (!("Skipped" in $$source)) {
            this["Skipped"] = 0;
        }
        if (!("Errors" in $$source)) {
            this["Errors"] = 0;
        }
        if (!("TotalFound" in $$source)) {
            this["TotalFound"] = 0;
        }
        if (!("ErrorMessages" in $$source)) {
            this["ErrorMessages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ErrorMessages" in $$parsedSource) {
            $$parsedSource["ErrorMessages"] = $$createField4_0($$parsedSource["ErrorMessages"]);
        }
        return new IndexResult($$parsedSource as Partial<IndexResult>);
    }
}

/**
 * PruneResult summarises a pruning run.
 */
export class PruneResult {
    "pruned": number;
    "checked": number;
    "errors": number;
    "errorMessages": string[];

    /** Creates a new PruneResult instance. */
    constructor($$source: Partial<PruneResult> = {}) {
        if (!("pruned" in $$source)) {
            this["pruned"] = 0;
        }
        if (!("checked" in $$source)) {
            this["checked"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = 0;
        }
        if (!("errorMessages" in $$source)) {
            this["errorMessages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PruneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PruneResult {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errorMessages" in $$parsedSource) {
            $$parsedSource["errorMessages"] = $$createField3_0($$parsedSource["errorMessages"]);
        }
        return new PruneResult($$parsedSource as Partial<PruneResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
