// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Model is one installed embedding model. Rows are created by importing a
 * .gguf through the UI or by scanning the models/ folder; per-model settings
 * live here and apply when the model is the active one.
 */
export class Model {
    "id": number;
    "name": string;
    "path": string;
    "dimensions": number;
    "contextWindow": number;
    "batchSize": number;
    "threads": number;
    "isActive": boolean;
    "created": string;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = 0;
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }
        if (!("threads" in $$source)) {
            this["threads"] = 0;
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

/**
 * QueryCacheStats summarises the query-vector cache for the Settings panel.
 */
export class QueryCacheStats {
    "entries": number;
    "bytes": number;

    /** Creates a new QueryCacheStats instance. */
    constructor($$source: Partial<QueryCacheStats> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryCacheStats instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryCacheStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryCacheStats($$parsedSource as Partial<QueryCacheStats>);
    }
}
