// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Filters holds optional filters for search queries.
 */
export class Filters {
    "collection": string;
    "sourceType": string;
    "path": string;
    "dateFrom": string;
    "dateTo": string;
    "sender": string;
    "author": string;
    "metadataFilters": { [_ in string]?: string };
    "topK": number;

    /** Creates a new Filters instance. */
    constructor($$source: Partial<Filters> = {}) {
        if (!("collection" in $$source)) {
            this["collection"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("dateFrom" in $$source)) {
            this["dateFrom"] = "";
        }
        if (!("dateTo" in $$source)) {
            this["dateTo"] = "";
        }
        if (!("sender" in $$source)) {
            this["sender"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("metadataFilters" in $$source)) {
            this["metadataFilters"] = {};
        }
        if (!("topK" in $$source)) {
            this["topK"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filters instance from a string or object.
     */
    static createFrom($$source: any = {}): Filters {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadataFilters" in $$parsedSource) {
            $$parsedSource["metadataFilters"] = $$createField7_0($$parsedSource["metadataFilters"]);
        }
        return new Filters($$parsedSource as Partial<Filters>);
    }
}

/**
 * SearchResponse is one search, mirrored to the frontend. Cached reports that
 * the query embedding was reused from the cache instead of recomputed; the
 * results themselves are always ranked fresh against the index.
 */
export class SearchResponse {
    "results": SearchResult[];
    "cached": boolean;

    /** Creates a new SearchResponse instance. */
    constructor($$source: Partial<SearchResponse> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("cached" in $$source)) {
            this["cached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResponse {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SearchResponse($$parsedSource as Partial<SearchResponse>);
    }
}

/**
 * SearchResult is a single search result, mirrored to the frontend.
 */
export class SearchResult {
    "content": string;
    "title": string;
    "metadata": { [_ in string]?: any };
    "score": number;
    "collection": string;
    "sourcePath": string;
    "sourceType": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("collection" in $$source)) {
            this["collection"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = SearchResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
