// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Config,
    GUIConfig,
    MCPConfig,
    MascotConfig,
    OCRConfig,
    SearchDefaults
} from "./models.js";
