// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config is the full application configuration.
 */
export class Config {
    "embedding_model": string;
    "embedding_batch_size": number;
    "chunk_size_tokens": number;
    "chunk_overlap_tokens": number;
    "obsidian_vaults": string[];
    "obsidian_exclude_folders": string[];
    "calibre_libraries": string[];
    "repositories": { [_ in string]?: string[] };
    "projects": { [_ in string]?: string[] };
    "disabled_collections": string[];
    "skip_cloud_placeholders": boolean;
    "git_history_in_months": number;
    "git_commit_subject_blacklist": string[];
    "search_defaults": SearchDefaults;
    "gui": GUIConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("embedding_model" in $$source)) {
            this["embedding_model"] = "";
        }
        if (!("embedding_batch_size" in $$source)) {
            this["embedding_batch_size"] = 0;
        }
        if (!("chunk_size_tokens" in $$source)) {
            this["chunk_size_tokens"] = 0;
        }
        if (!("chunk_overlap_tokens" in $$source)) {
            this["chunk_overlap_tokens"] = 0;
        }
        if (!("obsidian_vaults" in $$source)) {
            this["obsidian_vaults"] = [];
        }
        if (!("obsidian_exclude_folders" in $$source)) {
            this["obsidian_exclude_folders"] = [];
        }
        if (!("calibre_libraries" in $$source)) {
            this["calibre_libraries"] = [];
        }
        if (!("repositories" in $$source)) {
            this["repositories"] = {};
        }
        if (!("projects" in $$source)) {
            this["projects"] = {};
        }
        if (!("disabled_collections" in $$source)) {
            this["disabled_collections"] = [];
        }
        if (!("skip_cloud_placeholders" in $$source)) {
            this["skip_cloud_placeholders"] = false;
        }
        if (!("git_history_in_months" in $$source)) {
            this["git_history_in_months"] = 0;
        }
        if (!("git_commit_subject_blacklist" in $$source)) {
            this["git_commit_subject_blacklist"] = [];
        }
        if (!("search_defaults" in $$source)) {
            this["search_defaults"] = (new SearchDefaults());
        }
        if (!("gui" in $$source)) {
            this["gui"] = (new GUIConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("obsidian_vaults" in $$parsedSource) {
            $$parsedSource["obsidian_vaults"] = $$createField4_0($$parsedSource["obsidian_vaults"]);
        }
        if ("obsidian_exclude_folders" in $$parsedSource) {
            $$parsedSource["obsidian_exclude_folders"] = $$createField5_0($$parsedSource["obsidian_exclude_folders"]);
        }
        if ("calibre_libraries" in $$parsedSource) {
            $$parsedSource["calibre_libraries"] = $$createField6_0($$parsedSource["calibre_libraries"]);
        }
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField7_0($$parsedSource["repositories"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField8_0($$parsedSource["projects"]);
        }
        if ("disabled_collections" in $$parsedSource) {
            $$parsedSource["disabled_collections"] = $$createField9_0($$parsedSource["disabled_collections"]);
        }
        if ("git_commit_subject_blacklist" in $$parsedSource) {
            $$parsedSource["git_commit_subject_blacklist"] = $$createField12_0($$parsedSource["git_commit_subject_blacklist"]);
        }
        if ("search_defaults" in $$parsedSource) {
            $$parsedSource["search_defaults"] = $$createField13_0($$parsedSource["search_defaults"]);
        }
        if ("gui" in $$parsedSource) {
            $$parsedSource["gui"] = $$createField14_0($$parsedSource["gui"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * GUIConfig holds app-level (non-source) settings.
 */
export class GUIConfig {
    "auto_reindex": boolean;
    "auto_reindex_interval_minutes": number;
    "start_on_login": boolean;

    /** Creates a new GUIConfig instance. */
    constructor($$source: Partial<GUIConfig> = {}) {
        if (!("auto_reindex" in $$source)) {
            this["auto_reindex"] = false;
        }
        if (!("auto_reindex_interval_minutes" in $$source)) {
            this["auto_reindex_interval_minutes"] = 0;
        }
        if (!("start_on_login" in $$source)) {
            this["start_on_login"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GUIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GUIConfig($$parsedSource as Partial<GUIConfig>);
    }
}

/**
 * SearchDefaults holds the hybrid search parameters surfaced in Settings.
 */
export class SearchDefaults {
    "top_k": number;
    "rrf_k": number;
    "vector_weight": number;
    "fts_weight": number;

    /** Creates a new SearchDefaults instance. */
    constructor($$source: Partial<SearchDefaults> = {}) {
        if (!("top_k" in $$source)) {
            this["top_k"] = 0;
        }
        if (!("rrf_k" in $$source)) {
            this["rrf_k"] = 0;
        }
        if (!("vector_weight" in $$source)) {
            this["vector_weight"] = 0;
        }
        if (!("fts_weight" in $$source)) {
            this["fts_weight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchDefaults($$parsedSource as Partial<SearchDefaults>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = SearchDefaults.createFrom;
const $$createType3 = GUIConfig.createFrom;
