// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config is the full application configuration.
 */
export class Config {
    "embedding_model": string;
    "active_model": string;
    "embedding_batch_size": number;
    "chunk_size_tokens": number;
    "chunk_overlap_tokens": number;
    "obsidian_vaults": string[];
    "obsidian_exclude_folders": string[];
    "project_exclude_folders": string[];
    "calibre_libraries": string[];
    "repositories": { [_ in string]?: string[] };
    "projects": { [_ in string]?: string[] };
    "disabled_collections": string[];
    "skip_cloud_placeholders": boolean;
    "git_history_in_months": number;
    "git_commit_subject_blacklist": string[];
    "search_defaults": SearchDefaults;
    "gui": GUIConfig;
    "mcp": MCPConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("embedding_model" in $$source)) {
            this["embedding_model"] = "";
        }
        if (!("active_model" in $$source)) {
            this["active_model"] = "";
        }
        if (!("embedding_batch_size" in $$source)) {
            this["embedding_batch_size"] = 0;
        }
        if (!("chunk_size_tokens" in $$source)) {
            this["chunk_size_tokens"] = 0;
        }
        if (!("chunk_overlap_tokens" in $$source)) {
            this["chunk_overlap_tokens"] = 0;
        }
        if (!("obsidian_vaults" in $$source)) {
            this["obsidian_vaults"] = [];
        }
        if (!("obsidian_exclude_folders" in $$source)) {
            this["obsidian_exclude_folders"] = [];
        }
        if (!("project_exclude_folders" in $$source)) {
            this["project_exclude_folders"] = [];
        }
        if (!("calibre_libraries" in $$source)) {
            this["calibre_libraries"] = [];
        }
        if (!("repositories" in $$source)) {
            this["repositories"] = {};
        }
        if (!("projects" in $$source)) {
            this["projects"] = {};
        }
        if (!("disabled_collections" in $$source)) {
            this["disabled_collections"] = [];
        }
        if (!("skip_cloud_placeholders" in $$source)) {
            this["skip_cloud_placeholders"] = false;
        }
        if (!("git_history_in_months" in $$source)) {
            this["git_history_in_months"] = 0;
        }
        if (!("git_commit_subject_blacklist" in $$source)) {
            this["git_commit_subject_blacklist"] = [];
        }
        if (!("search_defaults" in $$source)) {
            this["search_defaults"] = (new SearchDefaults());
        }
        if (!("gui" in $$source)) {
            this["gui"] = (new GUIConfig());
        }
        if (!("mcp" in $$source)) {
            this["mcp"] = (new MCPConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType3;
        const $$createField17_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("obsidian_vaults" in $$parsedSource) {
            $$parsedSource["obsidian_vaults"] = $$createField5_0($$parsedSource["obsidian_vaults"]);
        }
        if ("obsidian_exclude_folders" in $$parsedSource) {
            $$parsedSource["obsidian_exclude_folders"] = $$createField6_0($$parsedSource["obsidian_exclude_folders"]);
        }
        if ("project_exclude_folders" in $$parsedSource) {
            $$parsedSource["project_exclude_folders"] = $$createField7_0($$parsedSource["project_exclude_folders"]);
        }
        if ("calibre_libraries" in $$parsedSource) {
            $$parsedSource["calibre_libraries"] = $$createField8_0($$parsedSource["calibre_libraries"]);
        }
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField9_0($$parsedSource["repositories"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField10_0($$parsedSource["projects"]);
        }
        if ("disabled_collections" in $$parsedSource) {
            $$parsedSource["disabled_collections"] = $$createField11_0($$parsedSource["disabled_collections"]);
        }
        if ("git_commit_subject_blacklist" in $$parsedSource) {
            $$parsedSource["git_commit_subject_blacklist"] = $$createField14_0($$parsedSource["git_commit_subject_blacklist"]);
        }
        if ("search_defaults" in $$parsedSource) {
            $$parsedSource["search_defaults"] = $$createField15_0($$parsedSource["search_defaults"]);
        }
        if ("gui" in $$parsedSource) {
            $$parsedSource["gui"] = $$createField16_0($$parsedSource["gui"]);
        }
        if ("mcp" in $$parsedSource) {
            $$parsedSource["mcp"] = $$createField17_0($$parsedSource["mcp"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * GUIConfig holds app-level (non-source) settings.
 */
export class GUIConfig {
    "auto_reindex": boolean;
    "auto_reindex_interval_minutes": number;
    "start_on_login": boolean;
    "mascot": MascotConfig;

    /** Creates a new GUIConfig instance. */
    constructor($$source: Partial<GUIConfig> = {}) {
        if (!("auto_reindex" in $$source)) {
            this["auto_reindex"] = false;
        }
        if (!("auto_reindex_interval_minutes" in $$source)) {
            this["auto_reindex_interval_minutes"] = 0;
        }
        if (!("start_on_login" in $$source)) {
            this["start_on_login"] = false;
        }
        if (!("mascot" in $$source)) {
            this["mascot"] = (new MascotConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GUIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GUIConfig {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mascot" in $$parsedSource) {
            $$parsedSource["mascot"] = $$createField3_0($$parsedSource["mascot"]);
        }
        return new GUIConfig($$parsedSource as Partial<GUIConfig>);
    }
}

/**
 * MCPConfig holds the in-app MCP (Model Context Protocol) server settings.
 * The server binds to 127.0.0.1 only. Search tools are always available;
 * AllowWrite gates the write tools (index/prune) that can change the library.
 */
export class MCPConfig {
    "enabled": boolean;
    "port": number;
    "allow_write": boolean;

    /** Creates a new MCPConfig instance. */
    constructor($$source: Partial<MCPConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("allow_write" in $$source)) {
            this["allow_write"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPConfig($$parsedSource as Partial<MCPConfig>);
    }
}

/**
 * MascotConfig controls which sidebar-mascot (Vexter) interactions are shown.
 * Each flag gates one resting-state trigger; all three off hides Vexter for
 * every moment at once.
 */
export class MascotConfig {
    "show_searching": boolean;
    "show_indexing": boolean;
    "show_nothing": boolean;

    /** Creates a new MascotConfig instance. */
    constructor($$source: Partial<MascotConfig> = {}) {
        if (!("show_searching" in $$source)) {
            this["show_searching"] = false;
        }
        if (!("show_indexing" in $$source)) {
            this["show_indexing"] = false;
        }
        if (!("show_nothing" in $$source)) {
            this["show_nothing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MascotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MascotConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MascotConfig($$parsedSource as Partial<MascotConfig>);
    }
}

/**
 * SearchDefaults holds the hybrid search parameters surfaced in Settings.
 */
export class SearchDefaults {
    "top_k": number;
    "rrf_k": number;
    "vector_weight": number;
    "fts_weight": number;

    /** Creates a new SearchDefaults instance. */
    constructor($$source: Partial<SearchDefaults> = {}) {
        if (!("top_k" in $$source)) {
            this["top_k"] = 0;
        }
        if (!("rrf_k" in $$source)) {
            this["rrf_k"] = 0;
        }
        if (!("vector_weight" in $$source)) {
            this["vector_weight"] = 0;
        }
        if (!("fts_weight" in $$source)) {
            this["fts_weight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchDefaults($$parsedSource as Partial<SearchDefaults>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = SearchDefaults.createFrom;
const $$createType3 = GUIConfig.createFrom;
const $$createType4 = MCPConfig.createFrom;
const $$createType5 = MascotConfig.createFrom;
