// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService exposes the in-process MCP server to the frontend. The server
 * binds to 127.0.0.1 only, so only AI clients on this machine can reach it.
 * Method names carry a "Server" suffix so they never collide with the Wails
 * service lifecycle hooks (Init/Start/Shutdown).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetMCPStatus returns the current server state.
 */
export function GetMCPStatus(): $CancellablePromise<$models.MCPStatus> {
    return $Call.ByID(2163182986).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartServer begins an MCP server on 127.0.0.1:port and returns the connection
 * URL clients should use. The transport is "streamable-http" (the default) or
 * "sse"; any other value falls back to streamable HTTP. Starting an
 * already-running server is a no-op that returns the current URL, unless the
 * requested transport differs from the live one.
 */
export function StartServer(port: number, transport: string): $CancellablePromise<string> {
    return $Call.ByID(4062741143, port, transport);
}

/**
 * StopServer shuts down whichever transport is running, with a short grace
 * period.
 */
export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2204354075);
}

// Private type creation functions
const $$createType0 = $models.MCPStatus.createFrom;
