// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MCPStatus is the live state of the MCP server, mirrored to the frontend.
 */
export class MCPStatus {
    "running": boolean;
    "port": number;
    "url": string;
    "transport": string;

    /** Creates a new MCPStatus instance. */
    constructor($$source: Partial<MCPStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("transport" in $$source)) {
            this["transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPStatus($$parsedSource as Partial<MCPStatus>);
    }
}
